version: '3.9'
services:
  nginx:
    container_name: nginx
    networks:
      - inception
    build: ./requirements/nginx/.
    image: nginx:hyounsi
    ports:
      - 443:443
    depends_on:
      - wordpress
    restart: always
    volumes:
      - wordpress:/var/www/wordpress
  mariadb:
    container_name: mariadb
    build: 
        context: ./requirements/mariadb/.
        args:
          DATABASE_NAME: ${DATABASE_NAME}
          DATABASE_USER_NAME: ${DATABASE_USER_NAME}
          DATABASE_USER_PASSWORD: ${DATABASE_USER_PASSWORD}
          DATABASE_ROOT_PASS: ${DATABASE_ROOT_PASS}
    image: mariadb:hyounsi
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
  wordpress:
    environment:
      DATABASE_USER_NAME: ${DATABASE_USER_NAME}
      DATABASE_USER_PASSWORD: ${DATABASE_USER_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      NEW_USER_NAME: ${NEW_USER_NAME}
      NEW_USER_PASSWORD: ${NEW_USER_PASSWORD}
      NEW_USER_EMAIL: ${NEW_USER_EMAIL}
      NEW_USER_ROLE: ${NEW_USER_ROLE}
    container_name: wordpress
    build: ./requirements/wordpress/.
    image: wordpress:hyounsi
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    restart: always
networks:
  inception:
    name: inception
volumes:
  mariadb:
    name: mariadb
    driver: local 
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/hyounsi/data/mariadb'
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/hyounsi/data/wordpress' 

    
    
    

    
