version: '3'
services:
  maraidb:
    container_name: maraidb
    build:
      context: ./requirements/mariadb/.
      args:
        DATABASE_NAME: ${DATABASE_NAME}
        DATABASE_USER_NAME: ${DATABASE_USER_NAME}
        DATABASE_USER_PASSWORD: ${DATABASE_USER_NAME} 
        DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    image: maraidb
    volumes:
      - web_data:/var/lib/mysql
volumes:
  web_data: