version: '3.9'
services:
  nginx:
    container_name: nginx
    networks:
      - inception
    build: ./requirements/nginx/.
    env_file:
      - .env
    ports:
      - 443:443
    depends_on:
      - wordpress
    restart: always
    volumes:
      - ./wordpress:/var/www/wordpress
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - inception
    # volumes:
    #   - ./mariadb:/var/lib/mysql
    env_file:
      - .env
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    networks:
      - inception
    volumes:
      - ./wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    restart: on-failure
    env_file:
      - .env
networks:
  inception:

    
    
    

    
