version: '3.9'
services:
  nginx:
    container_name: nginx
    networks:
      - inception
    build: ./requirements/nginx/.
    env_file:
      - .env
    ports:
      - 443:443
    depends_on:
      - wordpress
    restart: always
    volumes:
      - /home/hyounsi/data/wordpress:/var/www/wordpress
  mariadb:
    container_name: mariadb
    build: 
        context: ./requirements/mariadb/.
        args:
          DATABASE_NAME: ${DATABASE_NAME}
          DATABASE_USER_NAME: ${DATABASE_USER_NAME}
          DATABASE_USER_PASSWORD: ${DATABASE_USER_PASSWORD}
          DATABASE_ROOT_PASS: ${DATABASE_ROOT_PASS}
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
  wordpress:
    env_file:
      - .env
    container_name: wordpress
    build: ./requirements/wordpress/.
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    restart: on-failure
networks:
  inception:
volumes:
  mariadb:
    driver: local 
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/hyounsi/data/mariadb'
  wordpress:
    driver: local 
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/hyounsi/data/wordpress' 

    
    
    

    
