CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'hamza'@'%' IDENTIFIED BY 'hamza';
GRANT ALL PRIVILEGES ON wordpress.* TO 'hamza'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'hamza';



-- mysql -u root -p$DATABASE_ROOT_PASS <<EOF
-- CREATE DATABASE IF NOT EXISTS ${DATABASE_NAME};
-- CREATE USER IF NOT EXISTS '${DATABASE_USER_NAME}'@'%' IDENTIFIED BY '${DATABASE_USER_PASSWORD}';
-- GRANT ALL PRIVILEGES ON ${DATABASE_NAME}.* TO '${DATABASE_USER_NAME}'@'%';
-- FLUSH PRIVILEGES;
-- ALTER USER 'root'@'localhost' IDENTIFIED BY '${DATABASE_ROOT_PASS}';
-- EOF